# Generated by Django 5.2.1 on 2025-06-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_userprofile_photo_url_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_setting',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('marketing', 'Marketing')], default='email', max_length=20),
        ),
    ]
