# Generated by Django 5.2.1 on 2025-06-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userprofile_notification_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_setting',
            field=models.CharField(choices=[('telegram-notifications', 'Telegram notifications'), ('email-notifications', 'Email notifications'), ('marketing-notifications', 'Marketing notifications')], default='email', max_length=100),
        ),
    ]
